### ISSUE TITLE
Travis build fails due to GNU make version

### ISSUE THREAD

**Issue by rlepigre** [patoline/patoline#10]
I enable Travis CI builds for Patoline, but it fails with the following error. Do we already need GNU Make 4.0? Is the feature that we use essential?

```bash
0.01s$ make
GNUmakefile:60: 
****************************************************************************
****************************************************************************
**** This Makefile will soon require GNU Make version 4.0,
**** but you only have 3.81.
**** Please upgrade your GNU Make installation.
****************************************************************************
****************************************************************************
src/patfonts/Rules.mk:16: *** multiple target patterns.  Stop.
```

**Comment by flh** [comment]
GNU make 3.82 provides the "private" modifier for variables. Maintaining makefiles with generic rules without it is a nightmare and requires duplicating a lot of code.

GMake 3.82 was released 8 years ago. The version used by Travis CI is more than outdated.

**Comment by rlepigre** [comment]
I very much agree... Damn Debian and Ubuntu! I'm going to try and install a decent version from source in the Travis script then.

**Comment by flh** [comment]
You can only find GMake 3.81 in Debian oldstable. Even Debian stable has GMake 4.0. As for Ubuntu, only trusty still ships GMake 3.81: this LTS release is supported until next year (april 2019).

**Comment by rlepigre** [comment]
Right, they still use the old LTS version. Anyway, it seems to work now, and I just patched the configuration to compile the patobook. If you are interested in receiving Travis notifications in case of error, you can add your email address in the `.travis.yml`.
