### ISSUE TITLE
Does Patoline have an equivalent of \hbox and \vbox in TeX?

### ISSUE THREAD

**Issue by OlivierNicole** [patoline/patoline#12]
In plain TeX, one may write:
```tex
Hello \vbox{\hbox{you}\hbox{what}\hbox{is}\hbox{up}}
```
giving this result:

![screenshot_2018-05-04_21-51-40](https://user-images.githubusercontent.com/14031333/39649230-5c6d2f42-4fe5-11e8-9efb-1c785468f106.png)

Is there something similar to TeX's `\vbox` and, more generally, to TeX “vertical mode” in Patoline?

**Comment by OlivierNicole** [comment]
Even more generally, I'm trying to figure out whether it's possible to typeset text inside boxes, e.g. writing a paragraph inside a box in a diagram.

**Comment by rlepigre** [comment]
Patoline does not really have a built-in notion of box, but it would be possible to implement such a thing. For instance, I came up with [examples/stack_text.txp](https://github.com/patoline/patoline/blob/master/examples/stack_text.txp) for the example you give above. It looks like this:

![page_0](https://user-images.githubusercontent.com/1555539/39660176-79ca0aa2-5039-11e8-857c-aa2ee466923a.png)

For your second question, yes it is possible. You can insert arbitrary maths or text in diagram nodes (there are examples in the repository), and even paragraphs if you use a minipage. However, this is not very well documented, and I don't really have time to solve this problem right now. But do not hesitate to open issues and ask for help here!

**Comment by OlivierNicole** [comment]
Thanks for your answer. I'll look into `minipage`.

**Comment by tobiasBora** [comment]
For futur reference: the file is now [there](https://github.com/patoline/patoline/blob/master/tests/examples/stack_text.txp).
