### ISSUE TITLE
Error: Could not find the .cmi file for interface patconfig/patconfig.mli.

### ISSUE THREAD

**Issue by m4p-adm** [patoline/patoline#15]
On latest master ( a3336ab on Nov 23, 2018 ), on macos 10.14 with ocaml-base-compiler.4.05.0 following the steps
```
opam switch 4.05.0
eval $(opam env)
opam install dune earley.2.0.0 camlzip sqlite3 imagelib
wget https://github.com/patoline/patoline/archive/master.zip
unzip master.zip
cd patoline-master
make
```
results in 
```      ocamlc patconfig/.patconfig.objs/patconfig.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -nopervasives -nostdlib -g -bin-annot -I patconfig/.patconfig.objs -I patconfig/.patconfig.objs/.private -no-alias-deps -opaque -o patconfig/.patconfig.objs/patconfig.cmo -c -impl patconfig/patconfig.ml-gen)
File "patconfig/patconfig.ml-gen", line 1:
Error: Could not find the .cmi file for interface patconfig/patconfig.mli.
make: *** [all] Error 1  
```

Are there troubleshooting steps I could try?

**Comment by rlepigre** [comment]
That's really weird. What version of `dune` are you using? (Should be >= 1.2.0)

**Comment by m4p-adm** [comment]
Dune states 
```
dune --version             
1.6.3
```
so it should be ok.

**Comment by rlepigre** [comment]
Sorry I don't have any other idea right now. However, the problem is certainly dune-related, and I'm definitely not a dune expert. Maybe a change of behavior? I'm running dune 1.4.0 and everything works fine.

**Comment by m4p-adm** [comment]
Hm. Just downgraded, same result:
```
> opam install dune.1.4.0
The following actions will be performed:
  ↘ downgrade dune     1.6.3 to 1.4.0
  ↻ recompile jbuilder transition     [uses dune]
===== ↻ 1   ↘ 1 =====
Do you want to continue? [Y/n] y
[...]
⊘ removed   jbuilder.transition
⊘ removed   dune.1.6.3
∗ installed dune.1.4.0
∗ installed jbuilder.transition
Done.
[...]
> dune --version
1.4.0
>cd patoline-master/
>make clean
>make
      ocamlc patconfig/.patconfig.objs/patconfig.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -nopervasives -nostdlib -g -bin-annot -I patconfig/.patconfig.objs -I patconfig/.patconfig.objs/.private -no-alias-deps -opaque -o patconfig/.patconfig.objs/patconfig.cmo -c -impl patconfig/patconfig.ml-gen)
File "patconfig/patconfig.ml-gen", line 1:
Error: Could not find the .cmi file for interface patconfig/patconfig.mli.
make: *** [all] Error 1  


```

**Comment by rlepigre** [comment]
Have you tried compiling with `dune build --verbose` (instead of `make`)?

**Comment by m4p-adm** [comment]
Tried it now, with the same results (log shortened)
```
> dune build --verbose
Running[42]: (cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamldep.opt -modules -impl patconfig/patDefault.ml) > _build/default/patconfig/.patconfig.objs/patDefault.ml.d
Running[43]: (cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -nopervasives -nostdlib -g -bin-annot -I patconfig/.patconfig.objs -I patconfig/.patconfig.objs/.private -no-alias-deps -opaque -o patconfig/.patconfig.objs/patconfig.cmo -c -impl patconfig/patconfig.ml-gen)

Command [43] exited with code 2:
$ (cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -nopervasives -nostdlib -g -bin-annot -I patconfig/.patconfig.objs -I patconfig/.patconfig.objs/.private -no-alias-deps -opaque -o patconfig/.patconfig.objs/patconfig.cmo -c -impl patconfig/patconfig.ml-gen)
File "patconfig/patconfig.ml-gen", line 1:
Error: Could not find the .cmi file for interface patconfig/patconfig.mli.
Running[44]: (cd _build/default && /Users/xyz/.opam/4.05.0/bin/ocamldep.opt -modules -intf patconfig/configRC.mli) > _build/default/patconfig/.patconfig.objs/configRC.mli.d
```

Do you propose for me to dig into dune or is there a more promising path?

**Comment by rlepigre** [comment]
Frankly, I don't see how the problem could be due to Patoline. The problematic file correspond to the wrapped interface of some sublibrary, and it is supposed to be handled by dune. In particular, there is no corresponding source (`.ml` or `.mli`) file in the source tree. So yeah, I think investigating a bit more on the dune side could be a good option.

One thing to try may be to attempt to generate sublibraries of Patoline one at a time. But I'm not sure how to do that, so you can look at the documentation.

**Comment by jasdeep** [comment]
I am facing the same issue. It seems to mac specific and related to case sensitivity.  I tried renaming the files but no luck. I will have to rename the file references too.

@m4p-adm could you find any solution?

**Comment by pascalpoizat** [comment]
Hello

I did some renaming and I was able to compile under OSX.
See: https://github.com/pascalpoizat/patoline/commit/4393040f68f00096878e9d2e33918b5082f00967

Note: I did not know dune and OCaml before so I may have done some useless renamings (data types for examples). I will try to "remove" useless renamings later on.

**Comment by rlepigre** [comment]
OK, thanks. I'll try something in the same line, and I will also try to set up our CI to test OSX.

@pascalpoizat some of the things you did should not be useful indeed. I'll something similar of my own to see if that fixes the problem.

**Comment by rlepigre** [comment]
OK, the problem is fixed it would seem (I set up CI to also test on OSX). Feel free to reopen if that is not the case.

**Comment by pascalpoizat** [comment]
Thank you @rlepigre, I could clone+make under my system (OSX) without problem now.
