### ISSUE TITLE
Website down: http://patoline.org/

### ISSUE THREAD

**Issue by ComFreek** [patoline/patoline#23]
I get `ERR_NAME_NOT_RESOLVED` with my browser.

**Comment by aryx** [comment]
still down

**Comment by rlepigre** [comment]
I don't think any of us own this domain anymore, I removed any reference to it in af42a39f9774710f640fbbd9e4dd382bf80c8b27.

**Comment by aryx** [comment]
But the reference in the README  https://patoline.github.io seems to point internally to this domain.
You should set back patoline.github.io to not redirect to patoline.org

**Comment by rlepigre** [comment]
I have already done this I think.

**Comment by aryx** [comment]
yep it works now. Thx!
