### ISSUE TITLE
How to get the bibi executable?

### ISSUE THREAD

**Issue by jorsn** [patoline/patoline#24]
I built patoline using Nix with the patch from PR #21 and ocaml 4.07. However, I can build the patobook only without the bibliography, because I don't know where to get the `bibi` executable. Should it be built automatically by `dune build`?

In case this helps, this is the nix expression: <https://paste.sr.ht/~jorsn/0db971616b31488efe7e465be0d4d6b334a36174>

**Comment by rlepigre** [comment]
This is a separate tool, I uploaded the sources in this repository: https://github.com/patoline/hs-bibi

There is no instruction on how to compile it, and I don't directly remember. It is currently written in Haskell, but we should definitely rewrite that in OCaml and include it in the main patoline repository.

**Comment by jorsn** [comment]
Thank you very much!

With the patch in patoline/hs-bibi#1, bibi builds fine (`cabal build`/`cabal install`) and I can compile the patobook ([build log](https://paste.sr.ht/~jorsn/a0b6d6498fc772c02953ddf301cb91b25e7087ba)), including the bibliography, if I change the bibi call from `bibi biblio.bib` to `bibi -o biblio.bibi -d biblio.bib`.


I have no problem with Haskell as I can write it, but haven't written a line of *ML. ;)

For me it's fine to close the issue.

**Comment by rlepigre** [comment]
OK great!
