### ISSUE TITLE
compilation type error with RawContent.ml and ocaml 4.13.1

### ISSUE THREAD

**Issue by bdarcus** [patoline/patoline#28]
I think I have all the dependencies installed, but get this error when trying to compile with  ocaml 4.13.1.

```console
❯ make
File "patoraw/RawContent.ml", line 51, characters 14-36:
Error: This expression has type extension:string -> int * int
       but an expression was expected of type 'a * 'b
make: *** [GNUmakefile:3: all] Error 1  
```

It builds fine with ocaml 4.05.

**Comment by rlepigre** [comment]
Yeah, you're probably right. I'm having a look right now.

**Comment by bdarcus** [comment]
But when installing with 4.05, and trying to compile a document, I get this:

```console
File "hello_world.txp", line 1:
Error: /home/bruce/.opam/4.05.0/lib/patoline/patoraw/patoraw.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
OPT failed on ".patobuild/hello_world.ml"...
```

I'm not too familiar with ocaml.

**Comment by rlepigre** [comment]
You can try something like `eval $(opam env)` to make sure your opam environment is setup correctly in your shell. Then you might want to do `patoline --clean` to delete the `.patobuild` directory, and then invoke `patoline` again on the file you want to build.

Versions of OCaml newer than 4.07.1 are not supported due to the parser library we use (earley). We should rewrite the parser using something more robust I guess, but not sure if and when we'll do that.

**Comment by bdarcus** [comment]
> Versions of OCaml newer than 4.07.1 are not supported due to the parser library we use (earley). We should rewrite the parser using something more robust I guess, but not sure if and when we'll do that.

OK. But that package repo says "at least 4.07.0" (though doesn't appear very active).

> You can try something like ...

I'll experiment a bit.

Thanks!

**Comment by rlepigre** [comment]
> >Versions of OCaml newer than 4.07.1 are not supported due to the parser library we use (earley). We should rewrite the parser using something more robust I guess, but not sure if and when we'll do that.

> OK. But that package repo says "at least 4.07.0" (though doesn't appear very active).

Yeah, but that's only true for newer versions of `earley`, Patoline uses an older version since newer versions are kind of broken (to support newer OCaml).
