### ISSUE TITLE
Site is not working 

### ISSUE THREAD

**Issue by XVilka** [patoline/patoline#6]
Shows just 404

**Comment by flh** [comment]
Thanks for reporting this. The website has been down for about a week.

I'll try to see if we can bring it up again, and update it. (It used to provide slightly outdated information, especially on the installation procedure.)

**Comment by rlepigre** [comment]
I think we should host the website on GitHub for convenience, and ask @P-E-Meunier to redirect our old https://patoline.org to https://patoline.github.io. This will make modifications easier, and hopefully make the webpage more up to date.

Everything is set up on the https://github.com/patoline/patoline.github.io repository, we only need to update some of the informations some more.

Note that the website is now a simple HTML5 page with CSS, and does not rely on Haskell anymore. This was overkill anyway for such a small page.

**Comment by P-E-Meunier** [comment]
I've just updated it.

**Comment by rlepigre** [comment]
@P-E-Meunier do you mean you updated the server? There is still a 404 error on https://patoline.org.

**Comment by P-E-Meunier** [comment]
I've updated the DNS, as you asked. It might take time to propagate to caches.

**Comment by rlepigre** [comment]
OK cool! Thank you!

**Comment by XVilka** [comment]
I think it is not a DNS cache problem:
```
The connection has timed out
The server at patoline.org is taking too long to respond.
```

**Comment by rlepigre** [comment]
@P-E-Meunier can you have a look?

**Comment by flh** [comment]
patoline.org does not have any A record at all:
```
# dig patoline.org @root-dns.netcup.net

; <<>> DiG 9.11.2-P1-1-Debian <<>> patoline.org @root-dns.netcup.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27894
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;patoline.org.                  IN      A

;; AUTHORITY SECTION:
patoline.org.           86400   IN      SOA     root-dns.netcup.net. dnsadmin.netcup.net. 2018021300 28800 7200 1209600 86400

;; Query time: 37 msec
;; SERVER: 2a03:4000:0:1::e1e1#53(2a03:4000:0:1::e1e1)
;; WHEN: Fri Feb 16 12:04:39 CET 2018
;; MSG SIZE  rcvd: 105
```

@rlepigre: you should update GH patoline settings using the following instructions to declare the name "patoline.org" on GitHub webserver: https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
(I have no access to Patoline repositories settings.)

@P-E-Meunier: you can follow the instructions on https://help.github.com/articles/setting-up-an-apex-domain/ to set up the DNS records for patoline.org (ANAME/ALIAS or A record, depending on your DNS server).

**Comment by rlepigre** [comment]
@flh: I think I applied the required changes, but the DNS search obviously fails. I made you an owner of the `patoline` organisation as well, so now you should have full access to everything.
